<?php


function _datalogger_huongdan_quantri() {

  return <<< EOF
 <!-- DC PDF Embed Start -->
<iframe src="http://docs.google.com/viewer?url=http://113.160.225.111.8181.nyud.net/sites/domua.khituongthuyvan.net/files/huong-dan-admin.pdf&embedded=true" style="width:900px; height:500px;" frameborder="0">
    Your browser should support iFrame to view this PDF document</iframe>
<!-- DC PDF Embed End -->
EOF;

}

function _datalogger_huongdan_cactinh() {

  return <<< EOF
 <!-- DC PDF Embed Start -->
<iframe src="http://docs.google.com/viewer?url=http://113.160.225.111:8181/sites/domua.khituongthuyvan.net/files/huong-dan.pdf&embedded=true" style="width:900px; height:500px;" frameborder="0">
    Your browser should support iFrame to view this PDF document</iframe>
<!-- DC PDF Embed End -->
EOF;

}
